name: Merge Release/Hotfix Branch

on: 
 workflow_dispatch:

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set and cache global credentials
        run: |
          set -e
          git config --replace-all --global credential.helper "cache --timeout=3600"
          git config --global push.default simple
          git config --global user.email "tptls@hotmail.com"
          git config --global user.name "Github actions"

      - name: Extract Branch Name
        id: set_branch
        run: |
          full_branch_name="${GITHUB_REF}"
          stripped_branch_name="${full_branch_name#refs/heads/}"
          echo "BRANCH_NAME=${stripped_branch_name}" >> $GITHUB_ENV

      - name: Check if Branch Starts with Release or Hotfix
        run: |
          branch_name="${BRANCH_NAME}"
          if [[ "$branch_name" =~ ^(release|hotfix) ]]; then
            echo "Branch starts with 'release' or 'hotfix'."
          else
            echo "Branch does not start with 'release' or 'hotfix'."
            exit 1  # You might want to fail the workflow if the condition is not met.
          fi

      - name: Checkout release branch
        run: |
         git fetch --all
         git checkout ${BRANCH_NAME}
         git status
         git rev-parse --is-inside-work-tree
         git pull origin ${BRANCH_NAME}

      - name: Merge Release to Master
        run: |
          echo "Merging ${BRANCH_NAME} to master"
          git checkout master
          git pull origin master
          git merge "${BRANCH_NAME}" --no-ff
          git log --oneline --graph -n 5
          version=$(echo ${BRANCH_NAME}|sed 's:.*/::')
          git tag -a $version -m "$version"
          git push origin $version         
          git push origin master

      - name: Merge Release to Develop
        run: |
          set -e
          echo "Merging ${BRANCH_NAME} to develop"
          git checkout develop
          git pull origin develop
          git merge "${BRANCH_NAME}" --no-ff
          git push origin develop
