name: Merge Release/Hotfix Branch

on: 
 workflow_dispatch:

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set and cache global credentials
        run: |
          set -e
          git config --replace-all --global credential.helper "cache --timeout=3600"
          git config --global push.default simple
          git config --global user.email "tptls@hotmail.com"
          git config --global user.name "Github actions"

      - name: Set Branch Name
        id: set_branch
        run: echo "::set-output name=branch::$(echo "${GITHUB_REF#refs/heads/}")"

      - name: Merge Release to Develop
        run: |
          set -e
          branch=${{ steps.set_branch.outputs.branch }}
          echo "Merging ${branch} to develop"
          git checkout develop
          git pull origin develop
          git merge "${branch}" --no-ff
          git push origin develop

      - name: Merge Release to Master
        run: |
          set -e
          branch=${{ steps.set_branch.outputs.branch }}
          echo "Merging ${branch} to master"
          git checkout master
          git pull origin master
          git merge "${branch}" --no-ff
          git push origin master
